on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: fluffy-spoon/action
        with:
          gitHubToken: ${{ github.token }}